/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package at.fhv.kabi.samples.formatwriter.thrift.at.fhv.kabi.samples.formatwriter.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-02-11")
public class EcgThrift implements org.apache.thrift.TBase<EcgThrift, EcgThrift._Fields>, java.io.Serializable, Cloneable, Comparable<EcgThrift> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EcgThrift");

  private static final org.apache.thrift.protocol.TField SIGNALID_FIELD_DESC = new org.apache.thrift.protocol.TField("signalid", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField AFIB_FIELD_DESC = new org.apache.thrift.protocol.TField("afib", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new EcgThriftStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new EcgThriftTupleSchemeFactory();

  public int signalid; // required
  public int afib; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SIGNALID((short)1, "signalid"),
    AFIB((short)2, "afib");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SIGNALID
          return SIGNALID;
        case 2: // AFIB
          return AFIB;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SIGNALID_ISSET_ID = 0;
  private static final int __AFIB_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SIGNALID, new org.apache.thrift.meta_data.FieldMetaData("signalid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.AFIB, new org.apache.thrift.meta_data.FieldMetaData("afib", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EcgThrift.class, metaDataMap);
  }

  public EcgThrift() {
  }

  public EcgThrift(
    int signalid,
    int afib)
  {
    this();
    this.signalid = signalid;
    setSignalidIsSet(true);
    this.afib = afib;
    setAfibIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EcgThrift(EcgThrift other) {
    __isset_bitfield = other.__isset_bitfield;
    this.signalid = other.signalid;
    this.afib = other.afib;
  }

  @Override
  public EcgThrift deepCopy() {
    return new EcgThrift(this);
  }

  @Override
  public void clear() {
    setSignalidIsSet(false);
    this.signalid = 0;
    setAfibIsSet(false);
    this.afib = 0;
  }

  public int getSignalid() {
    return this.signalid;
  }

  public EcgThrift setSignalid(int signalid) {
    this.signalid = signalid;
    setSignalidIsSet(true);
    return this;
  }

  public void unsetSignalid() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SIGNALID_ISSET_ID);
  }

  /** Returns true if field signalid is set (has been assigned a value) and false otherwise */
  public boolean isSetSignalid() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SIGNALID_ISSET_ID);
  }

  public void setSignalidIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SIGNALID_ISSET_ID, value);
  }

  public int getAfib() {
    return this.afib;
  }

  public EcgThrift setAfib(int afib) {
    this.afib = afib;
    setAfibIsSet(true);
    return this;
  }

  public void unsetAfib() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __AFIB_ISSET_ID);
  }

  /** Returns true if field afib is set (has been assigned a value) and false otherwise */
  public boolean isSetAfib() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __AFIB_ISSET_ID);
  }

  public void setAfibIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __AFIB_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case SIGNALID:
      if (value == null) {
        unsetSignalid();
      } else {
        setSignalid((java.lang.Integer)value);
      }
      break;

    case AFIB:
      if (value == null) {
        unsetAfib();
      } else {
        setAfib((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case SIGNALID:
      return getSignalid();

    case AFIB:
      return getAfib();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case SIGNALID:
      return isSetSignalid();
    case AFIB:
      return isSetAfib();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof EcgThrift)
      return this.equals((EcgThrift)that);
    return false;
  }

  public boolean equals(EcgThrift that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_signalid = true;
    boolean that_present_signalid = true;
    if (this_present_signalid || that_present_signalid) {
      if (!(this_present_signalid && that_present_signalid))
        return false;
      if (this.signalid != that.signalid)
        return false;
    }

    boolean this_present_afib = true;
    boolean that_present_afib = true;
    if (this_present_afib || that_present_afib) {
      if (!(this_present_afib && that_present_afib))
        return false;
      if (this.afib != that.afib)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + signalid;

    hashCode = hashCode * 8191 + afib;

    return hashCode;
  }

  @Override
  public int compareTo(EcgThrift other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetSignalid(), other.isSetSignalid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSignalid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.signalid, other.signalid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAfib(), other.isSetAfib());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAfib()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.afib, other.afib);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("EcgThrift(");
    boolean first = true;

    sb.append("signalid:");
    sb.append(this.signalid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("afib:");
    sb.append(this.afib);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EcgThriftStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public EcgThriftStandardScheme getScheme() {
      return new EcgThriftStandardScheme();
    }
  }

  private static class EcgThriftStandardScheme extends org.apache.thrift.scheme.StandardScheme<EcgThrift> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, EcgThrift struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SIGNALID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.signalid = iprot.readI32();
              struct.setSignalidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // AFIB
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.afib = iprot.readI32();
              struct.setAfibIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, EcgThrift struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SIGNALID_FIELD_DESC);
      oprot.writeI32(struct.signalid);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(AFIB_FIELD_DESC);
      oprot.writeI32(struct.afib);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EcgThriftTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public EcgThriftTupleScheme getScheme() {
      return new EcgThriftTupleScheme();
    }
  }

  private static class EcgThriftTupleScheme extends org.apache.thrift.scheme.TupleScheme<EcgThrift> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EcgThrift struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetSignalid()) {
        optionals.set(0);
      }
      if (struct.isSetAfib()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetSignalid()) {
        oprot.writeI32(struct.signalid);
      }
      if (struct.isSetAfib()) {
        oprot.writeI32(struct.afib);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EcgThrift struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.signalid = iprot.readI32();
        struct.setSignalidIsSet(true);
      }
      if (incoming.get(1)) {
        struct.afib = iprot.readI32();
        struct.setAfibIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

