/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package at.fhv.kabi.samples.formatwriter.thrift.at.fhv.kabi.samples.formatwriter.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-02-11")
public enum ImageTypeThrift implements org.apache.thrift.TEnum {
  PNG(0),
  JPEG(1),
  SVG(2),
  GIF(3),
  TIFF(4),
  PDF(5);

  private final int value;

  private ImageTypeThrift(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ImageTypeThrift findByValue(int value) { 
    switch (value) {
      case 0:
        return PNG;
      case 1:
        return JPEG;
      case 2:
        return SVG;
      case 3:
        return GIF;
      case 4:
        return TIFF;
      case 5:
        return PDF;
      default:
        return null;
    }
  }
}
