// automatically generated by the FlatBuffers compiler, do not modify

package at.fhv.kabi.samples.formatwriter.flatbuffers.at.fhv.kabi.samples.formatwriter.flatbuffers;

@SuppressWarnings("unused")
public final class ImageType_FB {
  private ImageType_FB() { }
  public static final int PNG = 0;
  public static final int JPEG = 1;
  public static final int SVG = 2;
  public static final int GIF = 3;
  public static final int PDF = 4;

  public static final String[] names = { "PNG", "JPEG", "SVG", "GIF", "PDF", };

  public static String name(int e) { return names[e]; }
}

