// automatically generated by the FlatBuffers compiler, do not modify

package at.fhv.kabi.samples.formatwriter.flatbuffers.at.fhv.kabi.samples.formatwriter.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Person_FB extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static Person_FB getRootAsPerson_FB(ByteBuffer _bb) { return getRootAsPerson_FB(_bb, new Person_FB()); }
  public static Person_FB getRootAsPerson_FB(ByteBuffer _bb, Person_FB obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Person_FB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String fn() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer fnAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer fnInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String bday() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer bdayAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer bdayInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String gender() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer genderAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer genderInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String adr() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer adrAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer adrInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String email() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer emailAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer emailInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String tel() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer telAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer telInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String lang() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer langAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer langInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public String version() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer versionAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer versionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }

  public static int createPerson_FB(FlatBufferBuilder builder,
      int fnOffset,
      int bdayOffset,
      int genderOffset,
      int adrOffset,
      int emailOffset,
      int telOffset,
      int langOffset,
      int versionOffset) {
    builder.startTable(8);
    Person_FB.addVersion(builder, versionOffset);
    Person_FB.addLang(builder, langOffset);
    Person_FB.addTel(builder, telOffset);
    Person_FB.addEmail(builder, emailOffset);
    Person_FB.addAdr(builder, adrOffset);
    Person_FB.addGender(builder, genderOffset);
    Person_FB.addBday(builder, bdayOffset);
    Person_FB.addFn(builder, fnOffset);
    return Person_FB.endPerson_FB(builder);
  }

  public static void startPerson_FB(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addFn(FlatBufferBuilder builder, int fnOffset) { builder.addOffset(0, fnOffset, 0); }
  public static void addBday(FlatBufferBuilder builder, int bdayOffset) { builder.addOffset(1, bdayOffset, 0); }
  public static void addGender(FlatBufferBuilder builder, int genderOffset) { builder.addOffset(2, genderOffset, 0); }
  public static void addAdr(FlatBufferBuilder builder, int adrOffset) { builder.addOffset(3, adrOffset, 0); }
  public static void addEmail(FlatBufferBuilder builder, int emailOffset) { builder.addOffset(4, emailOffset, 0); }
  public static void addTel(FlatBufferBuilder builder, int telOffset) { builder.addOffset(5, telOffset, 0); }
  public static void addLang(FlatBufferBuilder builder, int langOffset) { builder.addOffset(6, langOffset, 0); }
  public static void addVersion(FlatBufferBuilder builder, int versionOffset) { builder.addOffset(7, versionOffset, 0); }
  public static int endPerson_FB(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishPerson_FBBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedPerson_FBBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Person_FB get(int j) { return get(new Person_FB(), j); }
    public Person_FB get(Person_FB obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

